### PR TITLE
Add maintainer

### PR DESCRIPTION
**Pull request by pierrsc**

### CODE REVIEW

**Comment by pierrsc** [comment]
@andrew-mcgrath
Please confirm that you still want to be a maintainer.

**Comment by pierrsc** [comment]
@conda-forge-admin, please rerender

**Comment by andrew-mcgrath** [comment]
> @andrew-mcgrath
> Please confirm that you still want to be a maintainer.

@pierrsc 👍

**Comment by pierrsc** [comment]
@conda-forge-admin, please update team

**Pull request merged**
